### ISSUE TITLE
How to select by index when there is more than one object by same id

### ISSUE THREAD

**Issue by vjyanand** [dtmilano/CulebraTester2-public#1]
`uiDevice/findObject?resourceId=com.google.android:id/row_simple_text_textview`. How to select nth element of `row_simple_text_textview`? Thanks

**Comment by dtmilano** [comment]
Not sure how you are invoking it (python?) but you can use

```
uiDevice/findObjects?bySelector=res@com.google.android:id/row_simple_text_textview
```
(notice the plural, Objects).

Then you can select the nth element of the array.

**Comment by vjyanand** [comment]
@dtmilano Unfortunately I don't find a route for it uiDevice/findObjects in [openapi.yaml](https://github.com/dtmilano/CulebraTester2-public/blob/master/openapi.yaml) Thanks again

**Comment by vjyanand** [comment]
Sorry for my overlook

**Comment by dtmilano** [comment]
@vjyanand no worries, it has been recently added.

It returns something like

```
[{'class_name': 'android.widget.TextView', 'oid': 1}, {'class_name': 'android.widget.TextView', 'oid': 2}, {'class_name': 'android.widget.TextView', 'oid': 3}, {'class_name': 'android.widget.TextView', 'oid': 4}, {'class_name': 'android.widget.TextView', 'oid': 5}, {'class_name': 'android.widget.TextView', 'oid': 6}]
```
