### ISSUE TITLE
Android Nougat

### ISSUE THREAD

**Issue by neervanbiqs** [dtmilano/CulebraTester2-public#14]
Is it possible to build apk to work on Android 7?

**Comment by dtmilano** [comment]
API 24 or 25?
Anyway, it might be possible with a few small changes.

**Comment by neervanbiqs** [comment]
API 25. Could you compile it? Or tell me how to do it. Thx!

**Comment by neervanbiqs** [comment]
I have successfully compiled apk for API 25. But I can't find Instrumentation apk in build folder. How to compile it?

**Comment by neervanbiqs** [comment]
already done, thx

**Comment by neervanbiqs** [comment]
got start-server error. java.time.Duration not found. it is API 26+ class. Do you have prev version without this class?

**Comment by neervanbiqs** [comment]
If I understand correctly I need your source code with Java ver up to 8

**Comment by dtmilano** [comment]
IIRC `java.time.Duration` was used by ktor.

**Comment by dtmilano** [comment]
Correct! take a look at https://youtrack.jetbrains.com/issue/KTOR-549

**Comment by neervanbiqs** [comment]
So there is no chance to install Culebra on API 25?

**Comment by dtmilano** [comment]
You can patch **ktor**, replace `java.time.Duration` by something available (IIRC it's just a few places), rebuild CulebraTester-public using the patched version and should work.

**Comment by dtmilano** [comment]
So as stated before it's not a **CulebraTester** issue. If you can get **ktor** compiling and working on API 25, then **CulebraTester** will work.
