### ISSUE TITLE
Dump via adb

### ISSUE THREAD

**Issue by neervanbiqs** [dtmilano/CulebraTester2-public#15]
Could you add the possibility to dump window via adb shell command like adb shell uiautomator dump?

**Comment by dtmilano** [comment]
If I understand correctly`/uiDevice/dumpWindowHierarchy` is what you are looking for.

Take a look at the API [here](https://mrin9.github.io/OpenAPI-Viewer/#/load/https%3A%2F%2Fraw.githubusercontent.com%2Fdtmilano%2FCulebraTester2-public%2Fmaster%2Fopenapi.yaml).

Not sure why you mentioned `adb shell` though. You can use `curl` if you want to do it just from the command line or script.

Check https://github.com/dtmilano/CulebraTester2-public/blob/master/dump-window-hierarchy

**Comment by dtmilano** [comment]
You can also use `git-bash` or [curl](https://curl.se/windows/) on Windows.

**Comment by dtmilano** [comment]
Or any HTTP client you like or [AndroidViewClient/culebra](https://github.com/dtmilano/AndroidViewClient)'s `dump -ah` that does precisely that.

**Comment by neervanbiqs** [comment]
Is it possible to click button via curl?

**Comment by dtmilano** [comment]
Yes, it might be easier using `python` but you can definitely do it using just `curl`.

Take a look at https://github.com/dtmilano/CulebraTester2-public/blob/master/simple-calculator-test.

Using `curl` it:
- Starts Calculator Activity
- Finds a Button corresponding to a digit (specified or random)
- Clicks that Button
