### ISSUE TITLE
Unable to start the server

### ISSUE THREAD

**Issue by KenLee12323** [dtmilano/CulebraTester2-public#19]
ERROR: Missing "android-select-device". Install from https://gist.github.com/dtmilano/4537110

Could you kindly tell me what do this mean? I tried to download and run the link's script, but then it required me to type in the adb server ip. I tired serval ip addresses but none of them work. 

Is there any step that I am missing? I have followed the steps in wiki/Start-server' one by one already. Thanks a lot for the help!

Below are the steps that I have done:
1. adb devices
2. bash ./culebratester2 start-server --local-port 5037

Error msg:
./culebratester2: line 140: tput: command not found
./culebratester2: line 141: tput: command not found
./culebratester2: line 142: tput: command not found
./culebratester2: line 143: tput: command not found
⛔️ ERROR: Missing "android-select-device". Install from https://gist.github.com/dtmilano/4537110

PS. I have already install the app and instrument apks in the phone and opened the app

**Comment by dtmilano** [comment]
So, what's the output of `adb devices`?

How is your device connected to `adb`, over wifi or USB?

What's the environment and operating system where you are running this?

I've noticed from your output `tput` command is not found either.

You don't have to specify `--local-port` unless you have multiple devices connected, is this your case?

**Comment by dtmilano** [comment]
https://github.com/dtmilano/CulebraTester2-public/commit/1ffbd1e60cb4cc25a156b4d52f728f2b234018f4 solves `tput` error on Windows.
