### ISSUE TITLE
Unable to download artifact.

### ISSUE THREAD

**Issue by ar1xwe** [dtmilano/CulebraTester2-public#20]
Sorry for being dumb, after 20 minutes I still cant figure out why cant I download the pre-built APK.

The builded file is not clickable(it should be, right?)

I also saw an issue about the artifact will expire? it's related?

**Comment by dtmilano** [comment]
No worries.
It is detailed at https://github.com/dtmilano/CulebraTester2-public/wiki/Prebuilt-APKs.

Artifacts expire after some time but the latest ones are from 2 weeks ago (so they are fine).
