### ISSUE TITLE
Guidance on Recording Function and File Export to Java, Python, Kotlin

### ISSUE THREAD

**Issue by chinhdl891** [dtmilano/CulebraTester2-public#23]
How does the recording function and self-exporting file to Java, Python, Kotlin work? Could you please guide me on how to use it? Thank you very much.

**Comment by dtmilano** [comment]
Only python code generation is available in the public repo.
You can start exploring it using [culebra](https://github.com/dtmilano/AndroidViewClient/wiki#culebra) command.

There are some screencasts available at https://github.com/dtmilano/AndroidViewClient/wiki/Resources#screencasts-and-videos which demonstrates some aspects of the code generation.

Feel free to ask questions here or in [stackoverflow](https://stackoverflow.com/questions/tagged/androidviewclient).

**Comment by chinhdl891** [comment]
Thank you very much. I was able to do it using the method you showed me. It's quite interesting. I want to learn more about using the UI to export to a JSON file. I've searched, but I don't know how to it. I saw a demo from three years ago, but I couldn't access localhost:3000 like in the video. Can you help me with that? I really appreciate it. Thank you <3

**Comment by dtmilano** [comment]
There's a UI available through Culebra GUI, which is probably what you used. Also, as I mentioned earlier, the web UI is not generally available.

If you have a more specific question about something you would like to accomplish, I could provide a more specific direction.

**Comment by chinhdl891** [comment]
I watched your video at https://www.youtube.com/watch?v=prE0aKoMLfc. I noticed that it can be converted to either Java or Kotlin code. I attempted to replicate it, but I couldn't follow the steps outlined in the video. Could you please guide me? I would greatly appreciate your help. Thank you.
![image](https://github.com/dtmilano/CulebraTester2-public/assets/92556577/538ac3c5-81ee-4e0b-abcb-9c2c921ceb08)
