### ISSUE TITLE
Instr.apk

### ISSUE THREAD

**Issue by neervanbiqs** [dtmilano/CulebraTester2-public#24]
Hi! I have successfully compiled apk_debug. But I can't find Instrumentation apk in build folder. How to compile it?

**Comment by neervanbiqs** [comment]
Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Failed to collect certificates from /data/app/vmdl1852737581.tmp/base.apk: Attempt to get length of null array]

**Comment by dtmilano** [comment]
Did you run
```
./gradlew installDebug installDebugAndroidTest
```
