### ISSUE TITLE
Cannot install android-select-device

### ISSUE THREAD

**Issue by canonsky1992** [dtmilano/CulebraTester2-public#4]
ERROR: Missing "android-select-device". Install from https://gist.github.com/dtmilano/4537110
Please tell me how to install it!! I use 'git clone https://gist.github.com/dtmilano/4537110' but not done!!

**Comment by dtmilano** [comment]
$ git clone https://gist.github.com/dtmilano/4537110
    $ ln -s $PWD/4537110/android-select-device ~/bin/

assuming `~/bin/` is in your PATH
