### ISSUE TITLE
Why I can not download Culebra Tester and Culebra Tester Instrumentation?

### ISSUE THREAD

**Issue by canonsky1992** [dtmilano/CulebraTester2-public#5]
Why I can not download Culebra Tester and Culebra Tester Instrumentation? Please help me!!

**Comment by dtmilano** [comment]
See https://github.com/dtmilano/CulebraTester2-public/wiki/Prebuilt-APKs

**Comment by Apeopex** [comment]
![image](https://user-images.githubusercontent.com/3247540/117220035-4d29b280-adbb-11eb-8866-35f20f1e722a.png)

Might be @canonsky1992's issue

**Comment by dtmilano** [comment]
I didn't know the maximum period is 90 days.
Need to build new ones.

**Comment by dtmilano** [comment]
https://github.com/dtmilano/CulebraTester2-public/actions/runs/815572695
